version: "3.9"

services:
  awa-api-nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8093:80
    mem_limit: "512M"
    volumes:
      - type: bind
        source: ./
        target: /usr/share/nginx/html/awa
      - type: bind
        source: ./docker/nginx/awa.conf
        target: /etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
    links:
      - awa-api-php

  awa-api-php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
      mem_limit: "512M"
      volumes:
        - type: bind
          source: ./
          target: /usr/share/nginx/html/awa
