const LANGUAGE = 'TOSHIN_LANGUAGE';
const TOSHIN_TOKEN = 'TOSHIN_TOKEN';
const TOSHIN_PROFILE = 'TOSHIN_PROFILE';
const TOSHIN_PICKER_YEAR_MONTH = 'TOSHIN_PICKER_YEAR_MONTH';
const TOSHIN_PICKER_WEEK = 'TOSHIN_PICKER_WEEK';
const LIST_COURSE_PATTERN = 'COURSE_PATTERN';
const INDEX_CALENDAR_WEEK_LIST_SHIFT = 'INDEX_CALENDAR_WEEK_LIST_SHIFT';

export default {
	LANGUAGE,
	TOSHIN_TOKEN,
	TOSHIN_PROFILE,
	TOSHIN_PICKER_YEAR_MONTH,
	TOSHIN_PICKER_WEEK,
	LIST_COURSE_PATTERN,
	INDEX_CALENDAR_WEEK_LIST_SHIFT,
};
