const TYPE_COURSE_PATTERN_ACTIVE = 'yes';
const TYPE_COURSE_PATTERN_NO_ACTIVE = 'no';
const TYPE_COURSE_PATTERN_DAPLICATE = 'duplicate';

const TEXT_COURSE_PATTERN_ACTIVE = '○';
const TEXT_COURSE_PATTERN_NO_ACTIVE = '×';
const TEXT_COURSE_PATTERN_DAPLICATE = '';

export default {
	TYPE_COURSE_PATTERN_ACTIVE,
	TYPE_COURSE_PATTERN_NO_ACTIVE,
	TYPE_COURSE_PATTERN_DAPLICATE,

	TEXT_COURSE_PATTERN_ACTIVE,
	TEXT_COURSE_PATTERN_NO_ACTIVE,
	TEXT_COURSE_PATTERN_DAPLICATE,
};
