const TYPE_DAY_OFF_FIXED_DAY_OFF = 'D-2';
const TYPE_DAY_OFF_DAY_OFF_REQUEST = 'D-3';
const TYPE_DAY_OFF_PAID = 'D-4';
const TYPE_DAY_OFF_DEFAULT = 'D-5';

const TEXT_DAY_OFF_FIXED_DAY_OFF = 'DAY_OFF.TABLE_DATE_FIXED_DAY_OFF';
const TEXT_DAY_OFF_DAY_OFF_REQUEST = 'DAY_OFF.TABLE_DATE_DAY_OFF_REQUEST';
const TEXT_DAY_OFF_PAID = 'DAY_OFF.TABLE_DATE_PAID';
const TEXT_DAY_OFF_DEFAULT = 'DAY_OFF.TABLE_DEFAULT';

const CLASS_DAY_OFF_FIXED_DAY_OFF = 'node-fixed-day-off';
const CLASS_DAY_OFF_DAY_OFF_REQUEST = 'node-day-off-request';
const CLASS_DAY_OFF_PAID = 'node-paid';
const CLASS_DAY_OFF_DEFAULT = 'node-default';

export default {
	TYPE_DAY_OFF_FIXED_DAY_OFF,
	TYPE_DAY_OFF_DAY_OFF_REQUEST,
	TYPE_DAY_OFF_PAID,
	TYPE_DAY_OFF_DEFAULT,

	TEXT_DAY_OFF_FIXED_DAY_OFF,
	TEXT_DAY_OFF_DAY_OFF_REQUEST,
	TEXT_DAY_OFF_PAID,
	TEXT_DAY_OFF_DEFAULT,

	CLASS_DAY_OFF_FIXED_DAY_OFF,
	CLASS_DAY_OFF_DAY_OFF_REQUEST,
	CLASS_DAY_OFF_PAID,
	CLASS_DAY_OFF_DEFAULT,
};
