const ROLE_DRIVER = 'driver';
const ROLE_SYSTEM_ADMINISTRATOR = 'admin';

const TEXT_ROLE_DRIVER = 'LIST_USER.ROLE_DRIVER';
const TEXT_ROLE_SYSTEM_ADMINISTRATOR = 'LIST_USER.ROLE_SYSTEM_ADMINISTRATOR';

export default {
	ROLE_DRIVER,
	ROLE_SYSTEM_ADMINISTRATOR,

	TEXT_ROLE_DRIVER,
	TEXT_ROLE_SYSTEM_ADMINISTRATOR,
};
