const TYPE_LIST_SCHEDULE_ACTIVE = 'on';
const TYPE_LIST_SCHEDULE_NO_ACTIVE = 'off';
const TYPE_LIST_SCHEDULE_NULL_DATA = 'null';

const TEXT_LIST_SCHEDULE_ACTIVE = '○';
const TEXT_LIST_SCHEDULE_NO_ACTIVE = '×';
const TEXT_LIST_SCHEDULE_NULL_DATA = '';

export default {
	TYPE_LIST_SCHEDULE_ACTIVE,
	TYPE_LIST_SCHEDULE_NO_ACTIVE,
	TYPE_LIST_SCHEDULE_NULL_DATA,

	TEXT_LIST_SCHEDULE_ACTIVE,
	TEXT_LIST_SCHEDULE_NO_ACTIVE,
	TEXT_LIST_SCHEDULE_NULL_DATA,
};
