const ENROLLMENT_STATUS_RETIRED = 'on';
const ENROLLMENT_STATUS_ENROLLED = 'off';

const TEXT_ENROLLMENT_STATUS_RETIRED = 'LIST_COURSE.ENROLLMENT_STATUS_RETIRED';
const TEXT_ENROLLMENT_STATUS_ENROLLED = 'LIST_COURSE.ENROLLMENT_STATUS_ENROLLED';

const LIST_FLAG = [
	{
		value: 'yes',
		text: 'CREATE_COURSE.YES',
	},
	{
		value: 'null',
		text: 'CREATE_COURSE.NULL',
	},
];

export default {
	ENROLLMENT_STATUS_RETIRED,
	ENROLLMENT_STATUS_ENROLLED,
	TEXT_ENROLLMENT_STATUS_RETIRED,
	TEXT_ENROLLMENT_STATUS_ENROLLED,

	LIST_FLAG,
};
